### ISSUE TITLE
trailingMargin problem lead to crash in v1.1.0 

### ISSUE THREAD

**Issue by jonz-tech** [SnapKit/Masonry#460] opened 2017-09-20 13:47 UTC
hello,it seems that a crash was made in the new version.Because the trailing margin was invalidate.
Plz check it.
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MASConstraintMaker trailingMargin]: unrecognized selector sent to instance
```
Thanks!

**Comment by robertjpayne** [comment] 2017-09-22 13:01
Dupe of #461

**Closed by robertjpayne** 2017-09-22 13:01 UTC
