### ISSUE TITLE
__IPHONE_OS_VERSION_MIN_REQUIRED not compile under iOS 11 SDK

### ISSUE THREAD

**Issue by ztlyyznf001** [SnapKit/Masonry#472] opened 2017-09-27 03:26 UTC
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [ ] I have looked at the [Documentation](https://github.com/SnapKit/Masonry/blob/master/README.md)
* [ ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                |  ios
 Platform Version        | 11.0
 Masonry Version         |  1.1.0
 Integration Method      | cocoapods
 

### Issue Description

⚠️ Replace this with the description of your issue. ⚠️ 

The methon under #if __IPHONE_OS_VERSION_MIN_REQUIRED 80000 does not compile, so it crashed with unrecognized methond, like leftmargin.

**Comment by robertjpayne** [comment] 2017-09-27 10:14
Dupe of #461

**Closed by robertjpayne** 2017-09-27 10:14 UTC
