### ISSUE TITLE
unrecognized selector sent to instance With Xcode 9

### ISSUE THREAD

**Issue by CainRun** [SnapKit/Masonry#469] opened 2017-09-26 03:22 UTC
### New Issue Checklist

* [x] I have looked at the [Documentation](https://github.com/SnapKit/Masonry/blob/master/README.md)
* [ ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 8.0~11.0
 Masonry Version         | 1.1.0
 Integration Method      | manually
 

### Issue Description

manualy masonry with Xcode 9 new project, prompt "unrecognized selector sent to instance", I promise that I have added -ObjC

**Comment by robertjpayne** [comment] 2017-09-27 10:14
Dupe of #461

**Closed by robertjpayne** 2017-09-27 10:14 UTC

**Comment by CainRun** [comment] 2017-09-27 11:52
This problem is solved and is the problem with Xcode 9, Thanks

**Comment by grandyang** [comment] 2017-11-12 05:53
Could you tell me how you solve it wit Xcode 9, thanks!

**Comment by eposa** [comment] 2017-11-29 11:37
@grandyang Try adding @objc to the declarations of request*. I had the same problem.
(i.e. replace `public func requestContacts() {` with `@objc public func requestContacts() {`)
